<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <xacro:property name="mPI" value="3.1415" />
  <xacro:property name="wheel_radius" value="0.08" />
  <xacro:property name="wheel_thickness" value="0.04" />
  <xacro:property name="chesis_length" value="0.3" />
  <xacro:property name="chesis_breadth" value="0.2" />
  <xacro:property name="chesis_height" value="0.08" />

  <xacro:macro name="box_inertia_" params="mass x y z">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="${(1/12)*mass*(y*y+z*z)}" ixy="0.0" ixz="0.0" iyy="${(1/12)*mass*(x*x+z*z)}" iyz="0.0" izz="${(1/12)*mass*(y*y+x*x)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cyl_inertia" params="mass r h">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="${(1/12)*mass*(3*r*r+h*h)}" ixy="0.0" ixz="0.0" iyy="${(1/2)*mass*r*r}" iyz="0.0" izz="${(1/12)*mass*(3*r*r+h*h)}"/>
    </inertial>
  </xacro:macro>

  <link name="chesis">
    <visual>
      <geometry>
        <box size="${chesis_length} ${chesis_breadth} ${chesis_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${chesis_length} ${chesis_breadth} ${chesis_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia_ mass="10" x="${chesis_length}" y="${chesis_breadth}" z="${chesis_height}"/>
  </link>

  <gazebo reference="chesis">
      <mu1 value="200.0"/>
      <mu2 value="100.0"/>
      <kp value="10000000.0" />
      <kd value="1.0" />
      <material>Gazebo/SkyBlue</material>
   </gazebo>

  <rgb_camera camera_name="armbot_rgb_camera" parent_link="chesis">
    <box size="0.001 0.008 0.008"/>
    <origin xyz="${(chesis_length/2)*1.001} 0 ${(chesis_height/2)*0.5}" rpy="0 0 0"/>
  </rgb_camera>
  <depth_camera camera_name="armbot_depth_camera" parent_link="chesis">
    <box size="0.001 0.08 0.01"/>
    <origin xyz="${(chesis_length/2)*1.001} 0 0" rpy="0 0 0"/>
  </depth_camera>

  <xacro:macro name="wheel" params="prefix suffix posx posy">
    <link name="${prefix}_${suffix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${mPI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${mPI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
      </collision>
      <xacro:cyl_inertia mass="1" r="${wheel_radius}" h="${wheel_thickness}"/>
    </link>
    <joint name="${prefix}_${suffix}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="chesis"/>
      <child link="${prefix}_${suffix}_wheel"/>
      <limit effort="30" velocity="4"/>
      <origin xyz="${(chesis_length*0.3)*posx} ${(chesis_breadth/2+wheel_thickness/2)*1.1*posy} 0" rpy="0 0 0"/>
    </joint>
    <gazebo reference="${prefix}_${suffix}_wheel">
      <mu1 value="200.0"/>
      <mu2 value="100.0"/>
      <kp value="10000000.0" />
      <kd value="1.0" />
      <material>Gazebo/DarkGrey</material>
    </gazebo>
    <transmission name="${prefix}_${suffix}_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="${prefix}_${suffix}_wheel_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="${prefix}_${suffix}_wheel_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
    </transmission>
  </xacro:macro>

  <xacro:wheel prefix="front" suffix="left" posx="1" posy="1"/>
  <xacro:wheel prefix="front" suffix="right" posx="1" posy="-1"/>
  <xacro:wheel prefix="back" suffix="left" posx="-1" posy="1"/>
  <xacro:wheel prefix="back" suffix="right" posx="-1" posy="-1"/>

</robot>