<?xml version="1.0"?>
<!-- Arm description for Turtlebot Arm and PhantomX Pincher arm -->
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find roboarm)/urdf/turtlebot_arm/arm_hardware.xacro"/>

  <material name="White">
    <color rgba="0.87 0.90 0.87 1.0"/>
  </material>
  <material name="Black">
    <color rgba="0.08 0.08 0.08 1.0"/>
  </material>
  <material name="Gray">
    <color rgba="0.2 0.2 0.21 1.0"/>
  </material>
  <material name="Green">
    <color rgba="0.22 0.32 0.14 1.0"/>
  </material>

  <xacro:macro name="turtlebot_arm" params="parent color pincher_gripper turtlebot_gripper gripper_color *origin">
    <link name="arm_base_link"/>
    <joint name="arm_base_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="arm_base_link"/>
    </joint>

    <!-- shoulder pan joint -->
    <xacro:dynamixel_AX12_fixed parent="arm_base_link" name="arm_shoulder_pan_servo">
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
    </xacro:dynamixel_AX12_fixed>
    <xacro:bioloid_F3_revolute parent="arm_shoulder_pan_servo_link" name="arm_shoulder_pan" color="${color}"
                         vlimit="${joints_vlimit}" llimit="${pan_llimit}" ulimit="${pan_ulimit}">
      <origin xyz="0 ${AX12_WIDTH/2} 0" rpy="${-M_PI/2} ${M_PI/2} ${M_PI}"/>
    </xacro:bioloid_F3_revolute>

    <!-- shoulder lift joint -->
    <xacro:dynamixel_AX12_fixed parent="arm_shoulder_pan_link" name="arm_shoulder_lift_servo">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${M_PI} 0"/>
    </xacro:dynamixel_AX12_fixed>
    <xacro:bioloid_F4_revolute parent="arm_shoulder_lift_servo_link" name="arm_shoulder_lift" color="${color}"
                         vlimit="${joints_vlimit}" llimit="${shoulder_llimit}" ulimit="${shoulder_ulimit}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:bioloid_F4_revolute>
    <xacro:bioloid_F10_fixed parent="arm_shoulder_lift_link" name="arm_shoulder_F10_0" color="${color}">
      <origin xyz="0 0 ${F4_HEIGHT+F10_HEIGHT/2}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>
    <xacro:bioloid_F10_fixed parent="arm_shoulder_F10_0_link" name="arm_shoulder_F10_1" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>
    <xacro:bioloid_F10_fixed parent="arm_shoulder_F10_1_link" name="arm_shoulder_F10_2" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>
    <xacro:bioloid_F3_fixed parent="arm_shoulder_F10_2_link" name="arm_shoulder_F3_0" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT/2}" rpy="0 ${M_PI} 0"/>
    </xacro:bioloid_F3_fixed>

    <!-- elbow joint -->
    <xacro:dynamixel_AX12_fixed parent="arm_shoulder_F3_0_link" name="arm_elbow_flex_servo">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${M_PI} 0"/>
    </xacro:dynamixel_AX12_fixed>
    <xacro:bioloid_F4_revolute parent="arm_elbow_flex_servo_link" name="arm_elbow_flex" color="${color}"
                         vlimit="${joints_vlimit}" llimit="${elbow_llimit}" ulimit="${elbow_ulimit}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:bioloid_F4_revolute>
    <xacro:bioloid_F10_fixed parent="arm_elbow_flex_link" name="arm_elbow_F10_0" color="${color}">
      <origin xyz="0 0 ${F4_HEIGHT+F10_HEIGHT/2}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>
    <xacro:bioloid_F10_fixed parent="arm_elbow_F10_0_link" name="arm_elbow_F10_1" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>
    <xacro:bioloid_F10_fixed parent="arm_elbow_F10_1_link" name="arm_elbow_F10_2" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>
    <xacro:bioloid_F3_fixed parent="arm_elbow_F10_2_link" name="arm_elbow_F3_0" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT/2}" rpy="0 ${M_PI} 0"/>
    </xacro:bioloid_F3_fixed>

    <!-- wrist joint -->
    <xacro:dynamixel_AX12_fixed parent="arm_elbow_F3_0_link" name="arm_wrist_flex_servo">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${M_PI} 0"/>
    </xacro:dynamixel_AX12_fixed>
    <xacro:bioloid_F2_revolute parent="arm_wrist_flex_servo_link" name="arm_wrist_flex" color="${color}"
                         vlimit="${joints_vlimit}" llimit="${wrist_llimit}" ulimit="${wrist_ulimit}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:bioloid_F2_revolute>

  <!-- gripper - Load either Turtlebot gripper or Pincher Gripper -->
  <xacro:if value="${pincher_gripper}">
  <xacro:include filename="$(find roboarm)/urdf/turtlebot_arm/pincher_gripper.xacro"/>
  </xacro:if>
  <xacro:if value="${turtlebot_gripper}">
  <xacro:include filename="$(find roboarm)/urdf/turtlebot_arm/turtlebot_gripper.xacro"/>
  </xacro:if>

  </xacro:macro>

</robot>
