<?xml version="1.0"?>
<!-- Turtlebot Arm gripper URDF-->
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:bioloid_F3_fixed parent="arm_wrist_flex_link" name="arm_wrist_F3_0" color="${color}">
      <origin xyz="0 0.016 ${F2_HEIGHT}" rpy="0 ${M_PI} ${-M_PI/2}"/>
    </xacro:bioloid_F3_fixed>
    <!-- gripper joint -->
    <xacro:dynamixel_AX12_fixed parent="arm_wrist_F3_0_link" name="gripper_servo">
      <origin xyz="-0.02275 0 ${-AX12_WIDTH/2}" rpy="${M_PI} ${M_PI/2} 0"/>
    </xacro:dynamixel_AX12_fixed>

    <!-- finger 1 -->
    <joint name="gripper_joint" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="1" velocity="0.785" lower="-0.40" upper="0.46"/>
      <parent link="gripper_servo_link"/>
      <child link="gripper_active_link"/>
    </joint>
    <link name="gripper_active_link">
      <inertial>
        <mass value="0.010"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="3.13e-6" ixy="0.0" ixz="0.0"
                 iyy="2.48e-6" iyz="0.0"
                 izz="1.69e-6"/>
      </inertial>
      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://roboarm/meshes/turtlebot_arm/F2.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
        </geometry>
        <material name="${color}"/>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 0.00775" rpy="0 0 0"/>
        <geometry>
          <box size="0.025 0.0375 0.0485"/>
        </geometry>
      </collision>
    </link>
    <xacro:finger_fixed parent="gripper_active_link" name="gripper_active_finger" color="${gripper_color}">
      <origin xyz="0 0 ${F2_HEIGHT}" rpy="0 0 0"/>
    </xacro:finger_fixed>

    <!-- finger 2 -->
    <xacro:bioloid_F3_fixed parent="gripper_servo_link" name="gripper_static" color="${color}">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${M_PI} 0"/>
    </xacro:bioloid_F3_fixed>
    <xacro:finger_fixed parent="gripper_static_link" name="gripper_static_finger" color="${gripper_color}">
      <origin xyz="0 0 0" rpy="0 0 ${M_PI}"/>
    </xacro:finger_fixed>

    <gazebo reference="gripper_static_finger_link">
			<mu1 value="100.0"/>
			<mu2 value="50.0"/>
			<kp value="10000000.0" />
			<kd value="1.0" />
		</gazebo>

    <gazebo reference="gripper_active_finger_link">
			<mu1 value="100.0"/>
			<mu2 value="50.0"/>
			<kp value="10000000.0" />
			<kd value="1.0" />
		</gazebo>

    <gazebo>
      <plugin name="gazebo_grasp_fix" filename="libgazebo_grasp_fix.so">
        <robotNamespace>/armbot</robotNamespace>
          <arm>
            <arm_name>armbot</arm_name>
            <gripper_link>gripper_active_link</gripper_link>
            <gripper_link>arm_wrist_flex_link</gripper_link>
            <palm_link>arm_wrist_flex_link</palm_link>
          </arm>   
        <forces_angle_tolerance>100</forces_angle_tolerance>
        <update_rate>4</update_rate>
        <grip_count_threshold>4</grip_count_threshold>
        <max_grip_count>8</max_grip_count>
        <release_tolerance>0.005</release_tolerance>
        <disable_collisions_on_attach>false</disable_collisions_on_attach>
        <contact_topic>__default_topic__</contact_topic>
      </plugin>
    </gazebo>
</robot>