armbot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  wheel_controller:
    type: "velocity_controllers/JointGroupVelocityController"
    pid: {p: 100.0, i: 0.01, d: 10.0}
    publish_rate: 50
    joints: ['front_left_wheel_joint', 'back_left_wheel_joint', 'front_right_wheel_joint', 'back_right_wheel_joint']
  
  mobile_base_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: ['front_left_wheel_joint', 'back_left_wheel_joint']
    right_wheel: ['front_right_wheel_joint', 'back_right_wheel_joint']
    publish_rate: 50
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
    cmd_vel_timeout: 0.25

    # Odometry fused with IMU is published by robot_localization, so
    # no need to publish a TF based on encoders alone.
    enable_odom_tf: false

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0 # default: 1.0
    wheel_radius_multiplier    : 1.0 # default: 1.0

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 2.0   # m/s
        has_acceleration_limits: true
        max_acceleration       : 20.0   # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 4.0   # rad/s
        has_acceleration_limits: true
        max_acceleration       : 25.0   # rad/s^2
  
  arm_controller:
    type: "position_controllers/JointGroupPositionController"
    joints: [arm_shoulder_pan_joint, arm_shoulder_lift_joint, arm_elbow_flex_joint, arm_wrist_flex_joint]
    #pid: {p: 100.0, i: 0.01, d: 10.0}
    publish_rate: 50
  
  arm_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_flex_joint
      - arm_wrist_flex_joint
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      arm_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      arm_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      arm_elbow_flex_joint: {trajectory: 0.1, goal: 0.1}
      arm_wrist_flex_joint: {trajectory: 0.1, goal: 0.1}
      gripper_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

  gripper:
    type: "position_controllers/GripperActionController"
    joint: gripper_joint