turtlebot_arm:

# maybe needed for real robot? from https://github.com/kbogert/phantomx_arm/tree/master/phantomx_arm_controller/config
# port: /dev/ttyUSB0
# read_rate: 15
# write_rate: 25
# joints: {
#     joint_1: {id: 1, max_angle: 3.8, min_angle: -0.5, max_speed: 90},
#     joint_2: {id: 2, max_angle: 2.1, min_angle: -2.0, max_speed: 90},
#     joint_3: {id: 3, max_angle: 2.1, min_angle: -2.0, max_speed: 90},
#     joint_4: {id: 4, max_angle: 1.5, min_angle: -1.5, max_speed: 90},
#     joint_5: {id: 5, max_angle: 0.1, min_angle: -2.7, max_speed: 90},
# }

  # Publish all joint states for rviz
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 40  

  # Arm Position Controller
  arm_controller:
    type: position_controllers/JointTrajectoryController
    joints: [arm_shoulder_pan_joint, arm_shoulder_lift_joint, arm_elbow_flex_joint, arm_wrist_flex_joint]
    constraints:
      goal_time: 10.0
      stopped_velocity_tolerance: 0.05   # I used to need a very large number because the shoulder lift joint still has a
      # stopped_velocity_tolerance: 0.3   # velocity even if stopped, aborting the execution as it never reaches the goal
      arm_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      arm_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      arm_elbow_flex_joint: {trajectory: 0.1, goal: 0.1}
      arm_wrist_flex_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

  arm_shoulder_pan_joint:
    type: position_controllers/JointPositionController
    joint: arm_shoulder_pan_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  arm_shoulder_lift_joint:
    type: position_controllers/JointPositionController
    joint: arm_shoulder_lift_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  arm_elbow_flex_joint:
    type: position_controllers/JointPositionController
    joint: arm_elbow_flex_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  arm_wrist_flex_joint:
    type: position_controllers/JointPositionController
    joint: arm_wrist_flex_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  # Gripper Position Controller
  gripper_controller:
    type: position_controllers/GripperActionController # used to be: position_controllers/JointPositionController, but MoveIt somehow can't handle this
    joint: gripper_joint  
    pid: {p: 100.0, i: 0.01, d: 10.0}

  # gazebo_ros_control:
  #  gains:
  #    arm_shoulder_pan_joint: {p: 100.0, i: 0.01, d: 10.0}
  #    arm_shoulder_lift_joint: {p: 100.0, i: 0.01, d: 10.0}
  #    arm_elbow_flex_joint: {p: 100.0, i: 0.01, d: 10.0}
  #    arm_wrist_flex_joint: {p: 100.0, i: 0.01, d: 10.0}
  #    gripper_joint: {p: 100.0, i: 0.01, d: 10.0}